#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_import_excel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Book1")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Test_import_excel.Properties.Settings.Default.Book1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Test> Tests
		{
			get
			{
				return this.GetTable<Test>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Test")]
	public partial class Test
	{
		
		private string _test_id;
		
		private string _test_name;
		
		private string _test_surname;
		
		private System.Nullable<int> _test_age;
		
		public Test()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_test_id", DbType="NChar(10)")]
		public string test_id
		{
			get
			{
				return this._test_id;
			}
			set
			{
				if ((this._test_id != value))
				{
					this._test_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_test_name", DbType="VarChar(50)")]
		public string test_name
		{
			get
			{
				return this._test_name;
			}
			set
			{
				if ((this._test_name != value))
				{
					this._test_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_test_surname", DbType="VarChar(100)")]
		public string test_surname
		{
			get
			{
				return this._test_surname;
			}
			set
			{
				if ((this._test_surname != value))
				{
					this._test_surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_test_age", DbType="Int")]
		public System.Nullable<int> test_age
		{
			get
			{
				return this._test_age;
			}
			set
			{
				if ((this._test_age != value))
				{
					this._test_age = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
